### ISSUE TITLE
docker-compose up command fails: 'The database for Neoscan.Repo couldn't be created: an exception was raised'

### ISSUE THREAD

**Issue by msied** [slipo/neo-scan-docker#2]
```
neo-scan       | 00:39:46.552 [error] GenServer #PID<0.4767.0> terminating
neo-scan       | ** (ArgumentError) argument error
neo-scan       |     (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
neo-scan       |     (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
neo-scan       |     (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
neo-scan       |     (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
neo-scan       |     (postgrex) lib/postgrex/protocol.ex:641: Postgrex.Protocol.bootstrap_send/6
neo-scan       |     (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
neo-scan       |     (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
neo-scan       |     (connection) lib/connection.ex:622: Connection.enter_connect/5
neo-scan       |     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
neo-scan       | Last message: nil
neo-scan       | State: Postgrex.Protocol
neo-scan       | ** (Mix) The database for Neoscan.Repo couldn't be created: an exception was raised:
neo-scan       |     ** (ArgumentError) argument error
neo-scan       |         (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
neo-scan       |         (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
neo-scan       |         (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
neo-scan       |         (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
neo-scan       |         (postgrex) lib/postgrex/protocol.ex:641: Postgrex.Protocol.bootstrap_send/6
neo-scan       |         (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
neo-scan       |         (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
neo-scan       |         (connection) lib/connection.ex:622: Connection.enter_connect/5
neo-scan       |         (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
neo-scan exited with code 1
```

This is the end result of `docker-compose up`. I made sure no other docker containers were running, and ran this after stopping/destroying the standalone privnet docker. It would be great to figure this out and add the solution to documentation as a (potentially) common gotcha.

**Comment by msied** [comment]
Appears related to this: https://github.com/elixir-ecto/postgrex/issues/368

**Comment by slipo** [comment]
Were you able to resolve this? That issue is apparently resolved.

**Comment by msied** [comment]
Resolution: in `docker-compose.yml` specify the postgres version. Set line 22 to `image: postgres:10.1`, then run `docker-compose pull`. After this, the startup command will work.
